# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` 

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [3]:
np.__version__

'1.26.4'

#### 3. Create a null vector of size 10

In [15]:
arr = np.zeros(10)

#### 4. How to find the memory size of any array 

In [19]:
arr.itemsize

8

#### 5. How to get the documentation of the numpy add function from the command line?

In [21]:
np.info()

 info(object=None, maxwidth=76, output=None, toplevel='numpy')

Get help information for an array, function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is
    an `ndarray` instance, information about the array is printed.
    If `object` is a numpy object, its docstring is given. If it is
    a string, available modules are searched for matching objects.
    If None, information about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``None``, in which case ``sys.stdout`` will be used.
    The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPyth

#### 6. Create a null vector of size 10 but the fifth value which is 1

In [25]:
arr = np.zeros(10)
arr[4]=1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49

In [27]:
arr = np.arange(10,49)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Reverse a vector (first element becomes last)

In [36]:
arr = np.arange(1,10)
new_arr=arr[::-1]
new_arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [40]:
arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [42]:
arr=[1,2,0,0,4,0]
new_arr=np.nonzero(arr)
new_arr

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix

In [46]:
arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [50]:
arr = np.random.random((3,3,3))
arr

array([[[0.74943053, 0.86296289, 0.28084816],
        [0.43488308, 0.06046357, 0.22104097],
        [0.95861316, 0.92760898, 0.50180167]],

       [[0.65964002, 0.68060562, 0.54363803],
        [0.48611281, 0.93582828, 0.26023789],
        [0.5787404 , 0.27124133, 0.14034728]],

       [[0.07577885, 0.66843998, 0.99531013],
        [0.05421852, 0.07968143, 0.98671937],
        [0.30627127, 0.75128823, 0.18406608]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [58]:
arr = np.random.random((10,10))
arr

array([[0.71452063, 0.26344222, 0.6087692 , 0.88166273, 0.6100999 ,
        0.98490893, 0.56501163, 0.03867348, 0.21502796, 0.03039098],
       [0.36984098, 0.15576686, 0.90597884, 0.0343517 , 0.85460108,
        0.29288112, 0.15456301, 0.08904626, 0.99974248, 0.28724987],
       [0.86752156, 0.6788411 , 0.64870057, 0.60674603, 0.94925239,
        0.83678962, 0.53439685, 0.67393953, 0.15968381, 0.81333192],
       [0.93455688, 0.41175527, 0.91691782, 0.12974022, 0.51628272,
        0.51990076, 0.72715978, 0.32212836, 0.91767196, 0.91812844],
       [0.97816818, 0.6028339 , 0.71012239, 0.51555366, 0.78248301,
        0.03802505, 0.10378197, 0.90016628, 0.36278954, 0.28288304],
       [0.42957898, 0.15065269, 0.86849377, 0.09691134, 0.84554529,
        0.60125805, 0.03758088, 0.60119071, 0.19453188, 0.69721569],
       [0.34294283, 0.92950921, 0.51375806, 0.18125256, 0.4835867 ,
        0.98749285, 0.12958459, 0.53499685, 0.47539746, 0.9252032 ],
       [0.81064764, 0.01567616, 0.5637351

In [60]:
arr.min()

0.015676158775025595

In [62]:
arr.max()

0.9997424829717689

#### 14. Create a random vector of size 30 and find the mean value

In [66]:
arr = np.random.random(10)
arr.mean()

0.5509984151463232

#### 15. Create a 2d array with 1 on the border and 0 inside

In [76]:
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

#### 16. How to add a border (filled with 0's) around an existing array?

In [78]:
arr = np.ones((3,3))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
arr

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression?
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [80]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [84]:
arr = np.diag([1, 2, 3, 4])
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [88]:
arr = np.ones((3,3))
print("checkboard pattern:")
arr = np.zeros((8,8),dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
arr

checkboard pattern:


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 

In [90]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function

In [94]:
arr = np.tile(np.array([[0,1],[1,0]]),(4,4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix

In [98]:
arr = np.random.random((5,5))
arr_max,arr_min = arr.max(), arr.min()
arr = (arr-arr_min)/(arr_max-arr_min)
arr

array([[0.7136094 , 0.00382187, 1.        , 0.54600645, 0.4325928 ],
       [0.72249263, 0.72827925, 0.68378337, 0.71649991, 0.25447808],
       [0.36932681, 0.77053014, 0.89343915, 0.57837999, 0.28613228],
       [0.79637811, 0.80875361, 0.06114776, 0.70957204, 0.88440956],
       [0.        , 0.36534333, 0.30814203, 0.20097885, 0.49749869]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [110]:
color = np.dtype([("r", np.ubyte, (1,)),
                  ("g", np.ubyte, (1,)),
                  ("b", np.ubyte, (1,)),
                  ("a", np.ubyte, (1,))])
color

dtype([('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [114]:
arr = np.dot(np.ones((5,3)),np.ones((3,2)))
arr

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [118]:
arr = np.arange(11)
arr[(3<arr)&(arr<=8)] *= 1
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 26. What is the output of the following script?
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [32]:
print(sum(range(5),-1))

10


In [34]:
from numpy import *
print(sum(range(5),-1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal?
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [6]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\world\AppData\Local\Temp\ipykernel_108\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\world\AppData\Local\Temp\ipykernel_108\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\world\AppData\Local\Temp\ipykernel_108\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ?

In [42]:
arr = np.random.uniform(-10,+10,10)
arr = np.copysign(np.ceil(np.abs(arr)),arr)
arr

array([  7., -10.,   9.,  -8.,   3., -10.,  10.,  -3.,   7.,  -9.])

#### 30. How to find common values between two arrays?

In [46]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)
result = np.intersect1d(arr1,arr2)
result

array([0, 2, 4, 7])

#### 31. How to ignore all numpy warnings (not recommended)?

In [48]:
defaults = np.seterr(all="ignore")
Z = np.ones(1)/0

_ = np.seterr(**defaults)

#### 32. Is the following expressions true?
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [51]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\world\AppData\Local\Temp\ipykernel_108\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow?

In [67]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
today = np.datetime64('today','D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
#yesterday 
#today 
#tomorrow

numpy.datetime64('2024-07-06')

#### 34. How to get all the dates corresponding to the month of July 2016?

In [69]:
arr = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(arr)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [71]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods

In [73]:
arr = np.random.uniform(0,10,10)
print (arr - arr%1)
print (np.floor(arr))
print (np.ceil(arr)-1)
print (arr.astype(int))
print (np.trunc(arr))

[0. 2. 4. 0. 7. 4. 4. 4. 5. 0.]
[0. 2. 4. 0. 7. 4. 4. 4. 5. 0.]
[0. 2. 4. 0. 7. 4. 4. 4. 5. 0.]
[0 2 4 0 7 4 4 4 5 0]
[0. 2. 4. 0. 7. 4. 4. 4. 5. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4

In [77]:
arr = np.zeros((5,5))
arr = arr + np.arange(5)
arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array

In [79]:
def generate():
    for x in range(10):
        yield x
arr = np.fromiter(generate(),dtype=float,count=-1)
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [81]:
arr = np.linspace(0,1,12,endpoint=True)[1:-1]
arr

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it

In [83]:
arr = np.random.random(10)
arr.sort()
arr

array([0.05201785, 0.06407906, 0.15361473, 0.19230288, 0.56147152,
       0.58795256, 0.61240168, 0.67885318, 0.96428255, 0.98241404])

#### 41. How to sum a small array faster than np.sum?

In [85]:
arr = np.arange(10)
np.add.reduce(arr)

45

#### 42. Consider two random array A and B, check if they are equal

In [93]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

arr = np.allclose(A,B)
arr = np.array_equal(A,B)
arr

False

#### 43. Make an array immutable (read-only) 

In [97]:
arr = np.zeros(10)
arr.flags.writeable = False
arr[0]=1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [101]:
arr = np.random.random((10,2))
x,y = arr[:,0],arr[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
r
t

array([1.08123009, 1.54073182, 0.82300774, 0.92860047, 0.34929009,
       0.32648297, 0.04037911, 1.10234952, 0.65717525, 0.04189455])

#### 45. Create random vector of size 10 and replace the maximum value by 0

In [103]:
arr = np.random.random(10)
arr[arr.argmax()] = 0
arr

array([0.4800103 , 0.11438405, 0.69659392, 0.39676428, 0.        ,
       0.85498792, 0.51404408, 0.39157692, 0.9205853 , 0.80323433])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

In [9]:
arr = np.zeros((5,5), [('x',float),('y',float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(arr)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [13]:
x = np.arange(8)
y = x + 0.5
C = 1/np.subtract.outer(x,y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type

In [15]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? 

In [21]:
arr = np.zeros((16,16))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector?

In [38]:
arr = np.arange(100)
ar = np.random.uniform(0,100)
print(arr,ar)
index = (np.abs(arr-ar)).argmin()
arr[index]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] 14.868837588691509


15

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [44]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
Z

C:\Users\world\AppData\Local\Temp\ipykernel_9572\1081022671.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [54]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.83209227 1.15824313 0.48554332 0.93517699 0.79593457
  0.20966764 0.48090858 0.55211796 0.5757039 ]
 [0.83209227 0.         0.84447612 0.73709709 0.38659746 0.46414059
  0.69857927 0.89119177 0.9387316  0.88582236]
 [1.15824313 0.84447612 0.         0.69992946 0.46117919 0.42875593
  0.94875069 0.8053848  0.78207794 0.71013769]
 [0.48554332 0.73709709 0.69992946 0.         0.62186212 0.43609176
  0.29143358 0.16068475 0.2016807  0.1571739 ]
 [0.93517699 0.38659746 0.46117919 0.62186212 0.         0.19057278
  0.74201495 0.77902268 0.79857576 0.72850803]
 [0.79593457 0.46414059 0.42875593 0.43609176 0.19057278 0.
  0.59204648 0.59090148 0.60831222 0.53796833]
 [0.20966764 0.69857927 0.94875069 0.29143358 0.74201495 0.59204648
  0.         0.33499416 0.40822859 0.41022897]
 [0.48090858 0.89119177 0.8053848  0.16068475 0.77902268 0.59090148
  0.33499416 0.         0.07356664 0.10591831]
 [0.55211796 0.9387316  0.78207794 0.2016807  0.79857576 0.60831222
  0.40822859 0.07356

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [52]:
z = np.arange(10,dtype=np.int32)
z = z.astype(np.float32,copy=False)
z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

#### 54. How to read the following file?
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [88]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.str_)
print(Z)

[['1' ' 2' ' 3' ' 4' ' 5']
 ['6' '  ' '  ' ' 7' ' 8']
 ['' '  ' ' 9' '10' '11']]


#### 55. What is the equivalent of enumerate for numpy arrays?

In [92]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array

In [98]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array?

In [100]:
n=10
p=3
z = np.zeros((n,n))
np.put(z,np.random.choice(range(n*n),p,replace=False),1)
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


#### 58. Subtract the mean of each row of a matrix

In [108]:
x = np.random.rand(5,10)
y = x-x.mean(axis=1,keepdims=True)
y = x-x.mean(axis=1).reshape(-1,1)
print(y)

[[ 0.23144027 -0.13921576  0.28846872 -0.38789771  0.37277987 -0.48086053
  -0.30687097  0.19234362  0.01404314  0.21576936]
 [ 0.328892   -0.07632752  0.07727199 -0.29064418 -0.21064498 -0.05016104
  -0.22344955  0.19050767 -0.00111071  0.25566631]
 [ 0.40762008 -0.25823692  0.01790353 -0.3133861  -0.07225618  0.1188118
  -0.33935109  0.10570325  0.38258336 -0.04939174]
 [ 0.01396122 -0.24573508 -0.16547243  0.19313994 -0.1894101  -0.30924741
   0.50742769  0.52195633 -0.14226214 -0.18435802]
 [-0.35611379 -0.14351522 -0.00415819 -0.13987971 -0.30870904  0.58733722
   0.47676194 -0.1074154   0.3932177  -0.39752551]]


#### 59. How to sort an array by the nth column?

In [111]:
z = np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[8 1 8]
 [2 8 3]
 [4 2 6]]
[[8 1 8]
 [4 2 6]
 [2 8 3]]


#### 60. How to tell if a given 2D array has null columns?

In [113]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array

In [115]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5021013091803019


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [117]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute

In [119]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [123]:
z = np.ones(10)
i = np.random.randint(0,len(z),20)
z += np.bincount(i,minlength=len(z))
print(z)
np.add.at(z,i,1)
print(z)

[2. 2. 2. 2. 6. 4. 3. 4. 2. 3.]
[ 3.  3.  3.  3. 11.  7.  5.  7.  3.  5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [125]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [137]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once?

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices?

#### 69. How to get the diagonal of a dot product?

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

#### 72. How to swap two rows of an array?

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

#### 75. How to compute averages using a sliding window over an array?

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

#### 77. How to negate a boolean, or to change the sign of a float inplace?

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? 

#### 88. How to implement the Game of Life using numpy arrays?

#### 89. How to get the n largest values of an array

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) 

#### 91. How to create a record array from a regular array?

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

#### 95. Convert a vector of ints into a matrix binary representation

#### 96. Given a two dimensional array, how to extract unique rows?

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).